name: Build LaTeX document
permissions: write-all
on: 
  push:
    branches: 
    - main
    - auto_latex_compile
jobs:
  build_and_upload_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: report_group14.tex
          working_directory: report_src
          args: -pdf -interaction=nonstopmode -shell-escape -f
      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add report_src/report_group14.pdf
          git commit -m "Auto-compiled LaTeX document [skip ci]"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git --force
